### ISSUE TITLE
[Feature Request] Simple version for dummies

### ISSUE THREAD

**Issue by stefanvladvoinea** [ecs87/AMD-GPU-Tool#5]
Although cool to set the values on 8 diff power levels it would be nice to have a simple version with less options (similar to Sapphire Trixx which is driving me crazy with bugs when it comes to multiple GPUs systems)

**Comment by ecs87** [comment]
I've had a few people request this but I've turned it down every time. I believe that every power level should be set properly. If I just made it so that the last (final; 100% GPU load) power level would be altered, during sudden increasing load the cards might draw more power than the last level (since the user didn't modify anything other than one plvl, the previous plvls may have voltage settings higher than the last plvl causing extremely high power draw on events such as DAG file loading during mining...which would cause them to blow their breakers).

**Comment by stefanvladvoinea** [comment]
I was more thinking to make it intelligent so you adjust the final value and the rest get adjusted behind the scenes following a predefined curve. The current features would be the expert mode and this one the basic mode. I'm mostly Java developer but I'm willing to help if you decide to make it open source (not just the gui)
